print("================================")
print("       VIDEX TRADING AI")
print("================================")
print()
print("System Status: READY")
print("AI Engine: ONLINE")
print("Market Analysis: READY")
print()
print("Welcome to VIDEX Trading AI!")
